name: Build and publish

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DavidKroell.TimeScoped.sln'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #      - name: Get Build Version
      #        run: |
      #          Import-Module .\build\GetBuildVersion.psm1
      #          Write-Host $Env:GITHUB_REF
      #          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
      #          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      #        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration $BUILD_CONFIG

      - name: Pack NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG -p:Version=${GITHUB_REF_NAME:1} --no-build

      - name: Publish NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}

